### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [MishaTsyba/template-JasonWood#1]
1. Убрать лишние nav, оставить один и сделать его фиксированным
2. тег `<p>` подразумевает текст, для таких `<p>TM</p>` коротких вставок используй `span`
3. Отвыкай от разного регистра в html, css `authorInfo` и такого много у тебя, не надо так
4. Лучше без h1, чем с таким `<h1>About Me</h1>`. тег <h1> представляет собой наиболее важный заголовок первого уровня.
5. normalize должен стоять первее всех.
6. Тебе w3c сто раз ругнется, что используя `section` надо бы ему и заголовок обьявить, иначе это не `section`. У тебя есть, что сделать заголовком, но ты это игноришь ... 
```
<section class="portfolio" id="portfolio">
<span>Portfolio</span>
```
7. Макет не адаптирован нормально. Я зашел с 1366 и у меня ощущение, что мне показывают мобильный вид. Мы говорили, начинай делать под компы уже с 1200px
8. Адаптивное меню совсем не юзабельно, подумай над UX. Тебе бы с телефона было бы ок на такое клацать? 
9. искаженные arrow-down очень кидаются в глаза, найди в svg
10. Очень большие отступы у секций http://joxi.ru/GrqyJ9LCQEPl1r
11. На мобильном как режет твою галлерейку слика. Есть практика показывать 1,5 картинки. Полностью текущую и половину следующей, таким образом юзер понимает, что можно потянуть и увидеть другое изображение
12. А почему такие стили просто к body не применить ?
```
a,
.logoText span,
.authorText h1,
.portfolio>span,
.contacts p:nth-child(4),
footer {
    font-family: 'nexa_lightregular', Arial, sans-serif;
    color: #d8d8d8;
```
13. h1 у тебя один и он вообще один на странице может быть и ты тут так стараешься, уточняешь, зачем? 
`.authorText>h1`

**Comment by MishaTsyba** [comment]
1 - 7 пп., 13 п. закрыл.
12 п. менять уже не буду, в будущем буду лучше организовывать стили.
Осталось пофиксить паддинги, слик, arrow-down и меню.

Что с меню делать, еще не придумал ...

**Comment by MishaTsyba** [comment]
Все баги закрыл
Осталось сделать адаптивное меню
